config/routes.rb
Rails.application.routes.draw do

  resources :dogs

  get 'donate' => 'site_pages#donate'
  get 'resources' => 'site_pages#resources'

  root 'site_pages#index'

end

app/models/concerns/animals.rb
module Animals
    extend ActiveSupport::Concern

    def age
        now = Time.now.utc.to_date
        now.year - birthday_at.year - (birthday_at.to_date.change(:year => now.year) > now ? 1 : 0)
    end

end

app/models/dog.rb
class Dog < ActiveRecord::Base

	include Animals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @animals = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :birthday_at, :description)
    end
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController

	def index
	end

	def donate
	end

	def resources
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav_link_to(text, href, opts = {})
		active_class = (current_page?(href) ? 'active' : nil)
		content_tag :li, link_to(text, href, opts), class: active_class
	end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/site_pages_helper.rb
module SitePagesHelper
end

app/views/animals/_list.html.erb
<div class="row">
	<% @animals.each do |animal| %>
	<div class="col-xs-6 col-sm-4 col-md-3">
		<div class="thumbnail auto-height">
			<%= link_to '', animal, class: 'animal-thumb', style: "background-image: url('http://upload.wikimedia.org/wikipedia/commons/5/5f/Pancho0008.JPG');" -%>
			<div class="caption">
				<h3>
					<%= animal.name -%>
					<small><%= animal.age -%></small>
				</h3>
				<%= animal.description -%>
			</div>
		</div>
	</div>
	<% end -%>
</div>

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
<% if @dog.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

  <ul>
    <% @dog.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :birthday_at %><br>
  <%= f.date_select :birthday_at, {}, {class: 'form-control form-group'} %>
</div>
<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_area :description, class: 'form-control' %>
</div>
<div class="actions">
  <%= f.submit nil, class: 'btn btn-primary' %>
</div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<div class="page-header">
	<%= content_tag :p, link_to('New Dog', new_dog_path), class: 'pull-right' if true -%>
	<h1>Dogs</h1>
	<p class="lead">Here you will find an active list of our current dogs available at the shelter. If you see an animal you like and wish to have more information you can <%= link_to 'call us', 'tel:1-352-596-7000' -%> or send an <%= link_to 'inquiry message', '#formModal' -%>.</p>
</div>



<%= render 'animals/list' -%>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @dog.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dog.description %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| -%>

	<% case key
	when 'notice'
		bs_class = 'info'
	when 'alert'
		bs_class = 'danger'
	else
		bs_class = 'warning'
	end -%>

	<%= content_tag :div, id: key, class: "alert alert-#{bs_class} alert-dismissable" do -%>
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= msg -%>
	<% end -%>

<% end -%>


<% if false; if current_user.password.nil? -%>
<div class="alert alert-warning alert-dismissible fade in" role="alert">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
	<h4>You do not have a password set!</h4>
	<%= content_tag :p, link_to('Set one now', edit_user_password_path, class: 'btn btn-primary') -%>
</div>
<% end; end -%>

app/views/layouts/_footer.html.erb
<hr>
<footer class="container">

	Copyright &copy; <%= Time.now.year -%> Kevin McCarthy. All Rights Reserved.
	<!-- Copyright &copy; <%= Time.now.year -%> SPCA of Hernando County. All Rights Reserved. -->

</footer>

app/views/layouts/_head.html.erb
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SPCA of Hernando</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>

	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

</head>

app/views/layouts/_header.html.erb
<header class="row">
	<div class="col-sm-8 col-sm-push-4 small" id="header-info">
		<p>
			9075 Grant St. Brooksville, FL 34613<br>
			11:00 AM - 4:00 - Daily<br>
			<a href="tel:1-352-596-7000">(352) 596-7000</a>
		</p>
	</div>
	<div class="col-sm-4 col-sm-pull-8">
		<%= link_to image_tag('logo-spca.png', id: 'logo'), root_url -%>
	</div>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'SPCA of Hernando County', root_url, class: 'navbar-brand' -%>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<!-- <ul class="nav navbar-nav"></ul> -->

			<ul class="nav navbar-nav navbar-right">
				<%= nav_link_to 'Cats', '#cats_path' -%>
				<%= nav_link_to 'Dogs', dogs_path -%>
				<%= nav_link_to 'Resources', resources_url -%>
				<%= nav_link_to 'News', '#news' -%>
				<%= nav_link_to 'Thrift Store', '#store' -%>
				<%= nav_link_to 'Donate', donate_url -%>
			</ul>
		</div><!-- /.navbar-collapse -->

	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' -%>
<body>

	<div class="container">
		<%= render 'layouts/header' -%>
		<%= render 'layouts/nav' -%>
		<%= render 'layouts/flash' -%>
		<%= yield %>
	</div>

	<%= render 'layouts/footer' -%>

</body>
</html>

app/views/site_pages/_form.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<form class="form">
			<fieldset>
				<legend>Contact Us</legend>
				<div class="form-group">
					<%= text_field_tag 'first_name', nil, placeholder: 'Full Name', class: 'form-control' -%>
				</div>
				<div class="form-group">
					<%= text_field_tag 'email', nil, placeholder: 'Email', class: 'form-control' -%>
				</div>
				<div class="form-group">
					<%= text_field_tag 'phone', nil, placeholder: 'Phone', class: 'form-control' -%>
				</div>
				<div class="form-group">
					<%= text_area_tag 'message', nil, placeholder: 'Your Message', class: 'form-control' -%>
				</div>

				<p class="small">SPCA will contact you via this form on all your inquiries. Please make sure to fill out the required fields (Name, Email, and Message), you may also add your phone number and other contact information.</p>

				<div class="form-group text-right">
					<button type="submit" class="btn btn-warning">Submit</button>
				</div>
			</fieldset>
		</form>
	</div>
</div>

app/views/site_pages/donate.html.erb
<div class="page-header">
	<h1>Donations & Gifts</h1>
	<p class="lead">
		The Society For The Prevention of Cruelty to Animals of Hernando County, Inc. is a nonprofit, no-kill, volunteer organization dedicated to the welfare of animals. All donations and gifts are tax deductable to the extent allowed by law.
	</p>
</div>



<section class="row">
	
	<div class="col-md-4">
		<h3>Our Wish List</h3>
		<div class="row">
			<div class="col-sm-6 col-md-12">
				<div class="panel panel-info">
					<div class="panel-body">
						<h4>For Dogs</h4>
						<ul>
							<li>
								Gift Cards for Kennels
								<ul>
									<li>Home Depot</li>
									<li>Lowes</li>
								</ul>
							</li>
							<li>Pedigree Canned Food</li>
							<li>Leashes</li>
							<li>Collars</li>
							<li><a href="http://www.critteroil.com" target="_blank">Critter Oil</a></li>
						</ul>
						<h4>For Cats</h4>
						<ul>
							<li>Friskies Canned Food</li>
							<li>Scoopable/Clumping Cat Litter</li>
							<li><a href="http://kuranda.com/donate/10304" target="_blank">Kuranda Cat Beds</a></li>
						</ul>
						<h4>For Staff</h4>
						<ul>
							<li>Fabuloso Cleaners (Any)</li>
							<li>Brooms</li>
							<li>Mop Heads</li>
							<li>Laundry Detergent</li>
							<li>Dawn (Blue)</li>
							<li>Disenfectant Wipes</li>
						</ul>
						<h4>For the Office</h4>
						<ul>
							<li>Stamps</li>
							<li>Ink Pens</li>
							<li>Copy Paper</li>
							<li>HP 564 Printer Ink (Black/Color)</li>
							<li>
								Batteries
								<ul>
									<li>AA</li>
									<li>9V</li>
								</ul>
							</li>
						</ul>
						<h4>Monetary Donations</h4>
						<ul>
							<li>To be used for Veterinary Care and Medications</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="col-sm-6 col-md-12 text-center">
				<div id='razoo_donation_widget'><span><a href="http://www.razoo.com/">Raise money online</a> for <a href="http://www.razoo.com/story/Society-For-The-Prevention-Cruelty-To-Animals-Of-Hernando-County">SOCIETY FOR THE PREVENTION CRUELTY TO ANIMALS OF HERNANDO COUNTY INC</a></span></div><script type='text/javascript'>var r_protocol=(("https:"==document.location.protocol)?"https://":"http://");var r_path='www.razoo.com/javascripts/widget_loader.js';var r_identifier='Society-For-The-Prevention-Cruelty-To-Animals-Of-Hernando-County';document.write(unescape("%3Cscript id='razoo_widget_loader_script' src='"+r_protocol+r_path+"' type='text/javascript'%3E%3C/script%3E"));</script>
			</div>

		</div>
	</div>
	<div class="col-md-8">
		<h3>Gifts</h3>
		<h4>Retirement Assets as Gifts</h4>
		Retirement assets are one of the most beneficial gifts you can give to the SPCA. These funds grow tax-free, until the time of withdrawal. With the innovative use of these assets, you are able to contribute generously to the SPCA as well as provide for your loved ones. Many taxes on these plans can be avoided or reduced through a carefully planned charitable gift.

		<h4>Gifts of Insurance</h4>
		Add a beneficiary to your policy. It is relatively simple to make a change to the beneficiary/beneficiaries of your insurance policy without changing your will or other aspects of your estate plan. Just ask your insurance company for a form that will allow you to make the SPCA a beneficiary of your insurance policy.

		<h4>Give a paid-up policy</h4>
		You can transfer ownership of a paid-up life insurance policy to the SPCA. After the transfer, the SPCA can elect to either cash in the policy right away or keep the policy and receive the death benefit later. You would receive an immediate income tax deduction for either the cash surrender value or the basis (usually the cost), whichever is less.

		<h4>Making the SPCA the owner and beneficiary</h4>
		You can take out a policy and make the SPCA the owner and beneficiary of the policy. Premium payments can be made by you directly to the insurance company. Your gift allows you to take an income tax deduction.

		<h4>Corporate Giving</h4>
		If you’re a business or corporation and are interested in fundraising on our behalf please email <a href="mailto:Ravenne64@gmail.com">luvnshelter@aol.com</a>.

		<h4>Dedication Gift</h4>
		You can further the SPCA’s lifesaving work and help build a humane country for all animals by providing a gift dedication to a loved one. It’s the perfect answer for holidays, birthdays or just because. An SPCA dedication gift makes a real difference in the fight to end animal cruelty and find permanent, loving homes for America’s adoptable pets.

		<h4>Honor Gift</h4>
		An Honor Gift is a wonderful way to celebrate the special people, animals and events in your life—and give the gift of life for animals in need. Thank you for making a difference today! With your honorary donation, we will mail a paper greeting card to the recipient and inform that person of your gift. After you submit your donation and receive a confirmation, you will be able to specify a mailing address and message for the card. Please allow 10-14 business days for delivery of the card.

		<h4>Memorial Gift</h4>
		A Memorial Gift is a beautiful testimony to the life of a beloved person or pet that has passed on—and the gift of life for animals in need. It can be just the right touch for expressing compassion to someone who has had a loss. With your memorial donation, we will mail a paper card to the recipient of your choice and inform that person of your gift. After you submit your donation and receive a confirmation, you will be able to specify a mailing address and message. Please allow 10-14 business days for delivery of the card.

		<h4>Vehicle Donation</h4>
		You can donate any car, truck – in good working condition – to help us save animals and get a tax deduction at the same time! It’s quick, easy and an all-around a win-win giving opportunity. What better way to get rid of an old or extra vehicle than turning it into the resources needed to support our animals? Through this simple act you will be helping the SPCA in our efforts to find permanent, loving homes for all our homeless pets. <a href="http://www.irs.gov/pub/irs-pdf/p4303.pdf" target="_blank">Find more information on donating a vehicle</a>.

		<h4>Food, Blanket Donations</h4>
		Are you collecting donations of pet food, toys or bedding for homeless animals? Unopened food, towels, bedding and toy donations may be dropped off at our Adoption Center located at 9075 Grant Street, Brooksville, Florida 34613 during our regular adoptions hours, Sunday to Saturday 11:00 A.M. – 4:00 P.M.

		<h4>Want to set up a workplace giving program at your company?</h4>
		Independent Charities of America operates GiveDirect, an online giving program that companies can use free of charge to manage either a year-round or an annual fund drive program.  100% of an employee’s pledge is passed on to their charity of choice. ICA can customize each company’s giving site to mirror the look and feel of the company’s own website or intranet site.  Companies can include some or all of ICA’s charity members, and they can add as many other charities to the list as they like.  There is also a back-end reporting website for company administrators and payroll personnel to generate reports and track pledges.
	</div>

</section>

app/views/site_pages/index.html.erb
<section class="row">
	<div class="col-sm-7 col-md-8 lead">
		We are a limited-space, no-kill humane shelter in which all animals are treated with respect and kindness. We provide temporary housing for the homeless, neglected and abandoned animals. Our Guiding Principles include providing our animals with freedom from hunger, thirst, discomfort, pain, injury, disease, and distress.
	</div>
	<div class="col-sm-5 col-md-4">
		<%= image_tag 'pets.jpg', class: 'img-responsive-center' -%>
	</div>
</section>

<section class="row">
	<div class="col-md-4">
		<hr class="visible-sm visible-xs">
		<div class="media">
			<div class="media-left">
				<%= image_tag 'icon-adopt.jpg', style: 'width: 64px; height: auto;' -%>
			</div>
			<div class="media-body">
				<h3 class="media-heading">Adopt</h3>
				<p>
					<div class="row">
						<div class="col-xs-6">
							<%= link_to 'Cats', '#cats_path', class: 'btn btn-info btn-md btn-block' -%>
						</div>
						<div class="col-xs-6">
							<%= link_to 'Dogs', dogs_path, class: 'btn btn-info btn-md btn-block' -%>
						</div>
					</div>
				</p>
				Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<hr class="visible-sm visible-xs">
		<div class="media">
			<%= link_to image_tag('icon-donate.png', style: 'width: 64px; height: auto;'), donate_url, class: 'media-left' -%>
			<div class="media-body">
				<h3 class="media-heading">Donate</h3>
				SPCA of Hernando County recieves no government funding. View our <%= link_to 'Donate', donate_url, class: 'label label-danger' -%> page to see a list of requested items. All donations and gifts are tax deductable to the extent allowed by law.
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<hr class="visible-sm visible-xs">
		<div class="media">
			<a class="media-left" href="#">
				<%= image_tag 'icon-volunteer.jpg', style: 'width: 64px; height: auto;' -%>
			</a>
			<div class="media-body">
				<h3 class="media-heading">Volunteer</h3>
				Cras sit amet nibh libero, in gravida nulla. Nulla vel <%= link_to 'Tour', '#', class: 'label label-success', data: {toggle: :modal, target: '#tourModal'} -%> metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
			</div>
		</div>
	</div>
</section>

<hr>

<section class="row">
	<div class="col-md-7">
		<h4>About the Society for the Prevention of Cruelty to Animals</h4>
		<p>
			Joyce Hudson and others were appalled by the lack of humane treatment afforded to many of the animals in Hernando County. Joyce’s efforts and persistence resulted in her becoming the head of the county Animal Control Services Department. After a while, Joyce left that post and with others, founded a corporation named the Animal Advisory Board. They operated out of various homes and garages. In 1984, the corporate name was changed to the Society for the Prevention of Cruelty to Animals. Joyce relocated and others, such as Rosalie Fredericks, carried on.
		</p>
		<p>
			There was going to be a shelter through many small fundraisers and a number of people concerned about the plight of the animals in our county, providing for them in their estate planning. One individual won the lottery and donated a sizeable sum to the organization. Land was purchased and the building started. This building would be used to house the animals, provide care for them, and to adopt out the animals. June 1995 was the grand opening of the shelter.
		</p>
		<%= content_tag :p, image_tag('https://www.aspca.org/sites/all/themes/aspca/logo.png'), class: 'text-center' -%>
	</div>
	<hr class="visible-sm visible-xs">
	<div class="col-md-5">
		<%= render 'site_pages/form' -%>
	</div>
</section>

<!-- Modal -->
<div class="modal fade" id="tourModal" tabindex="-1" role="dialog" aria-labelledby="tourModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="tourModalLabel">SPCA Tour</h4>
			</div>
			<div class="modal-body">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="//www.youtube.com/embed/Ylg6RkaFmMA?rel=0" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/site_pages/resources.html.erb
<section class="row">
	
	<div class="col-md-12">
		<h3>Intake Procedure</h3>
		<div class="panel panel-danger">
		<div class="panel-body">
		<p class="text-danger">
			<strong>All animals must be seen by a staff member before being accepted.</strong>
		</p>
		<p>
			<strong>Dogs 7 months or older:</strong><br>
			Must have a current rabies vaccine and a negative heartworm test. These vaccines can be obtained at your vet’s office or PetLuv clinic.
		</p>
		<p>
			<strong>Cats & Kittens:</strong><br>
			Must have a current rabies vaccine and a negative combo test. These vaccines can be obtained at your vet’s office or PetLuv clinic.
		</p>
		</div>
		</div>
	</div>
	<div class="col-sm-6">
		<h3>Safety & Vaccinations</h3>
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="//www.youtube.com/embed/UCuxPA_Ixzc?rel=0"></iframe>
		</div>
	</div>
	<div class="col-sm-6">
		<h3>Links</h3>
		<div class="panel panel-info">
			<div class="panel-body small">
				<a href="">PetLuv</a> - Non-Profit Animal Clinic.<br>
				<a href="">PetFinder</a> - Pet Adoption with search engine.<br>
				<a href="">PetPages</a> - Pet Resource Directory<br>
				<a href="">Facebook</a> - Our Facebook Page<br>
				<a href="">Tropicare</a> - Pest Control<br>
				<a href="">Radco</a><br>
				<a href="">Bargain Warehouse</a><br>
				<a href="">AJs Pump and Well</a><br>
				<a href="">Martinez Appliances</a>
			</div>
		</div>
	</div>
</section>

<section class="row">
	<div class="col-md-6">
		<h3>Heartworm Disease Information for Dogs</h3>
		<p>
			Heartworm disease acts very differently in dogs. Dogs are the definitive host for heartworm disease. This means dogs get an immature form of the worms from a mosquito, and the worms then mature to adults and reproduce in the dog.
		</p>
		<p>
			There are three blood tests that are routinely used to detect heartworm disease in small animals. The first is an occult heartworm test. this test is used in dogs that receive heartworm preventative during the mosquito season or ideally year round (heartgard, interceptor, etc.) and in dogs that are not on heartworm preventative. The test detects if there are adult heartworms present in the dog&#8217;s body by detecting proteins, or antigens, released by mature female heartworms. Since dogs with adult heartworms usually have lots of mature worms, there is usually a lot of antigen present to be detected. If a dog has a positive occult test, it has adult heartworms in its heart and/or pulmonary arteries. If a dog has a negative occult test, it does not have adult heartworms.
		</p>
		<p>
			The second heartworm test is a microfilaria or modified Knott&#8217;s test. Microfilarias are larva or immature forms of heartworms. Microfilarials tests detect larval heartworms that are either given to a dog from an infected mosquito or produced from adult heartworms living in the dog. Heartworm preventatives kill or prevent maturing of microfilaria, so this test in not performed on dogs receiving preventative. However, this test is preformed because a dog could have microfilaria without having adult worms if the dog is bitten by a mosquito carrying heartworm disease and the microfilaria have not had enough time to mature to adult heartworms.
		</p>
		<p>
			The third heartworm test is an antibody test. this test determines whether or not an animal has made antibodies against heartworm antigens. The test only tells veterinarians if the animal has been exposed to heartworms. It does not tell veterinarians whether or not an animal has heartworm infection in its body.
		</p>
		<p>
			Prevention is the key to preventing heartworm disease in our animals.
		</p>
	</div>
	<div class="col-md-6">
		<h3>Family and Your Pet</h3>
		<p>
			<strong>Kids and pets—a natural fit, right?</strong><br />
			Indeed, raising a child and pet together can be a lot of fun for the whole family, however creating healthy kid-pet relationships can be challenging and difficult. Here we offer tips to teach young members of the family to care for and &#8220;play nice&#8221; with their pets, helping to foster humane habits and a lifelong bond.
		</p>
		<p>Important ways to help prevent animal cruelty in your neighborhood:</p>
		<ol>
			<li>
				Contact your local law enforcement department and let them know that investigating animal cruelty should be a priority. Animal cruelty is a CRIME—and the police MUST investigate these crimes.
			</li>
			<li>
				Fight for the passage of strong anti-cruelty laws on federal, state and local levels. With stronger laws come tougher penalties. Write letters encouraging your legislators to pass these laws—and you can send them directly from our website.
			</li>
			<li>
				Set a good example for others. If you have pets, be sure to always show them the love and good care they deserve. But it&#8217;s more than just food, water, and adequate shelter. If you think your animal is sick, bring him to the veterinarian. Be responsible and have your animals spayed or neutered. And give your pets lots of hugs!
			</li>
			<li>
				Talk to your kids about how to treat animals with kindness and respect. Regularly we see children in homes where animal abuse has been reported. If a parent isn&#8217;t treating the family&#8217;s pets right, we tell the kids that their dog or cat would really appreciate fresh water every day or some daily playtime. If the animal has been left outside without shelter, we&#8217;ll say, &#8216;You have a nice house, and if you get cold, you can put a coat on. But your dog can&#8217;t do that.&#8217; Children need to understand that animals are living creatures that have the ability to feel pain, joy and sadness.
			</li>
			<li>
				Support your local shelter or animal rescue organization. It&#8217;s a great way to make a difference. Some of our SPCA volunteers foster animals that have been abused in their former homes, giving these dogs and cat the chance they deserve to have a good life. You can find a list of shelters and rescue groups in your area in by visiting petfinder.com/shelters.
			</li>
			<li>
				Start a Neighborhood Watch Program. Get to know the animals in your neighborhood and invite your friends and neighbors to do the same. Together you can keep an eye out for any suspicious behaviors—abuse and neglect of companion animals, the mistreatment of local wildlife, dogs left in hot cars.
			</li>
		</ol>
	</div>
</section>